version: '3.8'

services:
  client:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fonky-client
    # working_dir: /usr/src/fonky-client
    # volumes:
    #   - .:/usr/src/fonky-client
    networks:
      - fonky
    ports:
      - "${CLIENT_PORT}:3000"
    environment:
     CLIENT_PORT: ${CLIENT_PORT}
networks:
  fonky:
    driver: bridge
