version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fonky-server
    restart: always
    working_dir: /var/www/
    volumes:
      - .:/var/www
    networks:
      - fonky
  nginx:
    image: nginx:1.19-alpine
    container_name: fonky-nginx
    restart: always
    ports:
      - ${SERVER_PORT}:80
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - fonky
  db:
    container_name: fonky-mysql
    image: mysql:8.0
    volumes:
      - ./docker/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - fonky
networks:
  fonky:
    driver: bridge
